apiVersion: v2
name: krs
description: Intelligent Resource Optimization Controller for Kubernetes
type: application
version: 0.1.4
appVersion: "0.1.2"
home: https://github.com/joe-l-mathew/kube-resource-suggest
sources:
  - https://github.com/joe-l-mathew/kube-resource-suggest
maintainers:
  - name: joe-l-mathew
    url: https://github.com/joe-l-mathew
keywords:
  - kubernetes
  - monitoring
  - optimization
  - resources
  - prometheus
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/joe-l-mathew/kube-resource-suggest
  artifacthub.io/category: "monitoring"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
