apiVersion: v1
kind: ServiceAccount
metadata:
  name: krs-controller-sa
  namespace: krs-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krs-controller-role
rules:
  # 1. Read Workloads
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "statefulsets", "daemonsets", "nodes"]
    verbs: ["get", "list", "watch"]
  # 2. Manage Custom Resources
  - apiGroups: ["suggester.krs.io"]
    resources: ["resourcesuggestions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krs-controller-binding
subjects:
  - kind: ServiceAccount
    name: krs-controller-sa
    namespace: krs-monitoring
roleRef:
  kind: ClusterRole
  name: krs-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krs-controller
  namespace: krs-monitoring
  labels:
    app: krs-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krs-controller
  template:
    metadata:
      labels:
        app: krs-controller
    spec:
      serviceAccountName: krs-controller-sa
      containers:
        - name: controller
          image: kube-resource-suggest:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PROMETHEUS_URL
              value: "http://krs-prometheus-svc:9090"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
