apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-resource-suggest.serviceAccountName" . }}
  labels:
    {{- include "kube-resource-suggest.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-resource-suggest.fullname" . }}
  labels:
    {{- include "kube-resource-suggest.labels" . | nindent 4 }}
rules:
  # 1. Read Workloads
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "statefulsets", "daemonsets", "nodes", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
  # 2. Manage Custom Resources
  - apiGroups: ["suggester.krs.io"]
    resources: ["resourcesuggestions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-resource-suggest.fullname" . }}
  labels:
    {{- include "kube-resource-suggest.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-resource-suggest.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-resource-suggest.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.openshift.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-resource-suggest.fullname" . }}-openshift-monitoring
  labels:
    {{- include "kube-resource-suggest.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-resource-suggest.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
{{- end }}
